name: Java CI with Maven

on:
  push:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
  pull_request_target:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: x86_64-pc-linux
          move: mv
          separator: /
          extension: ""
        - os: macos-latest
          platform: x86_64-apple-darwin
          move: mv
          separator: /
          extension: ""
        - os: windows-latest
          platform: x86_64-pc-win32
          move: move
          separator: \
          extension: .exe
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.5.0
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/sonatype username | SONATYPE_USERNAME ;
          kv/data/cicd/sonatype password | SONATYPE_PASSWORD ;
          kv/data/cicd/gpg secring | GPG_SECRING ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17.0.7'
        distribution: 'graalvm'
        native-image-job-reports: 'true'
    - name: Build bfc
      run: |
        mkdir dist
        ./mvnw -V --no-transfer-progress package -Pnative
        ${{ matrix.move }} target${{ matrix.separator }}bfc${{ matrix.extension }} dist${{ matrix.separator }}bfc-${{ matrix.platform }}${{ matrix.extension }}
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - name: Revoke token
      if: always()
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self
